# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
