# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 01:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 11, 1, 1, 52, 57, 905705, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
